In [ ]:
Numpy >> Numerical Python

import numpy
import numpy as np

Numpy : Numpy is a base library in python that deals with numbers. it is used to perform different mathematical operations on n dimensional array.
    
A numpy array is a homogeneous data type array which means it assigns one perticular kind of data type to an entire array.

It is time efficients. 
It has so many mathematical operations.
-Probability
-Linear algebra
- matrix related operators
-Geometry
- Statastics
- Logarithmic maths
-Random number generation


In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
list1 = [2,3,4,5]
type(list1)

list

In [3]:
array =np.array([2,3,4,5])
type(array)

numpy.ndarray

# how to check the dimensions of array

In [4]:
array =np.array([2,3,4,5])
array.ndim

1

In [5]:
array =np.array([[2,3,4,5]])
array.ndim

2

In [6]:
array =np.array([[2,3],
                 [4,5]])
array.ndim

2

In [7]:
array =np.array([[[2,3],
                 [4,5]]])
array.ndim

3

# how to convert a lower dimension into higher dimension array

In [8]:
array =np.array([2,3,4,5],ndmin=2)
array.ndim

2

In [9]:
array

array([[2, 3, 4, 5]])

In [12]:
array =np.array([2,3,4,5],ndmin=3)
array.ndim,array

(3, array([[[2, 3, 4, 5]]]))

# how to convert a list into array

In [13]:
list1 = [2,3,4,5]
array = np.array(list1)
array

array([2, 3, 4, 5])

In [14]:
l1 = 2,3,4
arr = np.array(l1)
type(arr)

numpy.ndarray

# Can an array have multiple data types?

In [21]:
# bcz 1 itme is string so all items are converted into string
array =np.array([2,3.9,'4',-5])
print(array)
type(array[1])

['2' '3.9' '4' '-5']


numpy.str_

In [17]:
array =np.array([2,3.9,4,-5])
array

array([ 2. ,  3.9,  4. , -5. ])

In [18]:
array =np.array([2,3.9,4+3j,-5])
array

array([ 2. +0.j,  3.9+0.j,  4. +3.j, -5. +0.j])

In [19]:
array =np.array([2,3.9,4,-5],dtype='int')
array

array([ 2,  3,  4, -5])

In [20]:
array =np.array([2,3,4,-5],dtype='float')
array

array([ 2.,  3.,  4., -5.])

In [22]:
array =np.array([2,3,4,-5],dtype='complex')
array

array([ 2.+0.j,  3.+0.j,  4.+0.j, -5.+0.j])

In [23]:
array =np.array([2,3,4,-5],dtype='str')
array

array(['2', '3', '4', '-5'], dtype='<U2')

In [27]:
# object sets the data types to default data type of the elements int the array
array =np.array([2,3,'4',-5],dtype='object')
print(array)
type(array[1])
type(array[2])

[2 3 '4' -5]


str

In [29]:
import pandas as pd
array =np.array([2,3,'4',-5])
df = pd.DataFrame(array)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       4 non-null      object
dtypes: object(1)
memory usage: 160.0+ bytes


# Indexing

In [31]:
array =np.array([2,3,4,5])
array[0]

2

In [32]:
array[-1]

5

In [34]:
array[-1:1:-1]

array([5, 4])

In [35]:
array = np.array([[[2,3,6,6],
                   [3,2,3,9],
                   [5,6,5,0]],
                  
                  [[2,3,4,2],
                   [3,3,4,6],
                   [7,8,9,0]]])
print(array)

[[[2 3 6 6]
  [3 2 3 9]
  [5 6 5 0]]

 [[2 3 4 2]
  [3 3 4 6]
  [7 8 9 0]]]


In [36]:
array[0]

array([[2, 3, 6, 6],
       [3, 2, 3, 9],
       [5, 6, 5, 0]])

In [38]:
array[0][0][1]

3

In [39]:
array[1][-1][1]

8

# slicing

In [40]:
array =np.array([2,3,4,5])
array[1:-1]

array([3, 4])

In [41]:
array =np.array([2,3,4,5,1,4,0,8,6,3,4])
array[1:10:2]

array([3, 5, 4, 8, 3])

In [51]:
arr = np.array([[2, 3, 6, 6],
                [3, 2, 3, 9],
                [5, 6, 5, 0]])

arr[1:][1:][0][1:]

array([6, 5, 0])

In [52]:
array = np.array([[[2,3,6,6],
                   [3,2,3,9],
                   [5,6,5,0]],
                  
                  [[2,3,4,2],
                   [3,3,4,6],
                   [7,8,9,0]]])
print(array)

[[[2 3 6 6]
  [3 2 3 9]
  [5 6 5 0]]

 [[2 3 4 2]
  [3 3 4 6]
  [7 8 9 0]]]


In [55]:
array[0][1][0:2]

array([3, 2])

In [62]:
# in this example we have 2 rows & 3 columns
arr = np.array([[2,3,4],
                [5,6,7]])
arr                        # horizontal are rows & vertical are columns

array([[2, 3, 4],
       [5, 6, 7]])

In [63]:
arr[:,:]          # all rows & all columns

array([[2, 3, 4],
       [5, 6, 7]])

In [64]:
arr = np.array([[2,3,4],
                [5,6,7],
                [8,9,0]])

arr[0:2,1:]            # initially we describe rows & then we describe columns

array([[3, 4],
       [6, 7]])

In [65]:
array = np.array([[[2,3,6,6],
                   [3,2,3,9],
                   [5,6,5,0]],
                  
                  [[2,3,4,2],
                   [3,3,4,6],
                   [7,8,9,0]]])
print(array[0:,1:,1:-1])

[[[2 3]
  [6 5]]

 [[3 4]
  [8 9]]]


In [66]:
array[:,1:,2:]

array([[[3, 9],
        [5, 0]],

       [[4, 6],
        [9, 0]]])

In [68]:
array = np.array([[[[2,3,6,6],
                    [3,2,3,9],
                    [5,6,5,0]],
                  
                   [[2,3,4,2],
                    [3,3,4,6],
                    [7,8,9,0]]],
                  
                  [[[0,0,0,0],
                    [0,0,0,0],
                    [0,0,0,0]],
                  
                   [[2,3,4,2],
                    [3,3,4,6],
                    [7,8,9,0]]]])

array[:,1:,-1:,1:-1]

array([[[[8, 9]]],


       [[[8, 9]]]])

In [71]:
array[:,1:,:2,:2]

array([[[[2, 3],
         [3, 3]]],


       [[[2, 3],
         [3, 3]]]])

# Reshape

In [73]:
arr = np.array([1,2,3,4,5,6,7,8,9,0,1,2])
len(arr)

12

In [74]:
arr = arr.reshape(1,12)
arr

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2]])

In [75]:
arr = arr.reshape(12,1)
arr

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9],
       [0],
       [1],
       [2]])

In [79]:
arr = arr.reshape(2,6)
arr = arr.reshape(6,2)
arr = arr.reshape(3,4)
arr = arr.reshape(4,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]])

In [80]:
arr = np.array([1,2,3,4,5,6,7,8,9,0,2])
arr.reshape(3,4)

ValueError: cannot reshape array of size 11 into shape (3,4)

In [81]:
arr = np.array([1,2,3,4,5,6,7,8,9,0,2,1])
arr.reshape(3,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 0],
        [2, 1]]])

In [82]:
arr.reshape(2,3,2)

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[7, 8],
        [9, 0],
        [2, 1]]])

In [83]:
arr.reshape(2,2,3)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 2, 1]]])

# converting n rray into list

In [89]:
arr = np.array([1,2,3,4,5,6,7,8,9,0,2,1])
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 2, 1])

In [90]:
list(arr)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 2, 1]

In [91]:
my_list = arr.tolist()
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 2, 1]

In [92]:
array= np.array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 0],
        [2, 1]]])

array.tolist()

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 0], [2, 1]]]

# how to create an empty array

In [95]:
array = np.array([],dtype='int')
array

array([], dtype=int32)

# creating an array of matrix zeros

In [99]:
arr = np.zeros((5),dtype='int')
arr

array([0, 0, 0, 0, 0])

In [98]:
arr = np.zeros((5,5),dtype='int')
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [102]:
arr = np.zeros((5,2,3),dtype='int')
arr

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

# creating a matrix of ones

In [103]:
arr = np.ones(5,dtype='float')
arr

array([1., 1., 1., 1., 1.])

In [104]:
arr = np.ones((5,6),dtype='int')
arr

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [105]:
arr = np.ones((5,2,3),dtype='int')
arr

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

# creating a sequence of array using arange function

In [106]:
np.array(list(range(1,11)))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [112]:
numbers = np.arange(-1,-11,-2,dtype='float')
print(numbers)
len(numbers)

[-1. -3. -5. -7. -9.]


5

In [114]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# eye()

In [115]:
np.eye(3,dtype='I')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=uint32)

In [116]:
np.eye(5,dtype='I')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=uint32)

In [118]:
np.eye(4,5,dtype='I')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=uint32)

In [119]:
np.eye(4,5,dtype='I',k=2)        # positive values of k -- shift along column

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]], dtype=uint32)

In [120]:
np.eye(4,5,dtype='I',k=-2)       # negative values of k -- shift is along rows

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]], dtype=uint32)

# Indentity()

In [121]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [123]:
np.identity(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [126]:
np.identity(5,4,dtype='int')

TypeError: 'tuple' object cannot be interpreted as an integer

In [127]:
np.identity(5,dtype='int',k=2)

TypeError: identity() got an unexpected keyword argument 'k'