In [1]:
import numpy as np

In [8]:
A = np.array([[3,4],
              [5,6]])
B = np.array([15,20])

result = np.linalg.solve(A,B)
result

array([-5. ,  7.5])

In [10]:
x = result[0]
y = result[1]
x,y

(-5.000000000000005, 7.500000000000005)

In [14]:
A = np.array([[3,4,-5],[3,0,7],[0,4,-2]])
B = np.array([25,30,15])

np.linalg.solve(A,B)

array([5.33333333, 4.75      , 2.        ])

In [15]:
3*5.33333333+4*4.75 -5*2

24.99999999

In [17]:
np.around(np.linalg.solve(A,B),1)

array([5.3, 4.8, 2. ])